### ISSUE TITLE
Write error

### ISSUE THREAD

**Issue by albertoRamon** [jingw/pyhdfs#11]
Hello 
Mkdir and listdir work fine
But create didn't

```
fs.create('/fruit/apple', 'delicious')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/miniconda2/lib/python2.7/site-packages/pyhdfs.py", line 426, in create
    metadata_response.headers['location'], data=data, **self._requests_kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda2/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='1566bb80c4dc', port=50075): Max retries exceeded with url: /webhdfs/v1/fruit/apple?op=CREATE&user.name=hdfs&namenoderpcaddress=localhost:8020&overwrite=false (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f644f364510>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

**Comment by jingw** [comment]
mkdir and listdir are NameNode-only operations. In contrast, create requires access to the DataNodes. See https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#CREATE and make sure your datanode is accessible from the computer where your code is running.

**Comment by albertoRamon** [comment]
I found it, FYI:
(Thanks)

![screenshot from 2018-09-27 00-32-16](https://user-images.githubusercontent.com/15262462/46113048-2495b100-c1ed-11e8-9c29-017e1cec57e1.png)

**Comment by albertoRamon** [comment]
The port is open, 210ada7beb04 is the name of container
_http://**210ada7beb04**:50075/webhdfs/v1/_

Was a problen with resolution Name
Thanks

**Comment by jingw** [comment]
Sorry, I don't know how your network is set up, and I can't help with it :(
