### ISSUE TITLE
HdfsFileAlreadyExistsException is not implemented?

### ISSUE THREAD

**Issue by james77777778** [jingw/pyhdfs#20]
Hi!
Thanks for your great work.
I have noticed that some Exceptions are not implemented right now?

For example:
If I try to upload the file with same path, the python raises ConnectionError instead of HdfsFileAlreadyExistsException.

error message as following:
```bash
Traceback (most recent call last):
  File "test_pyhdfs.py", line 12, in <module>
    fs.create('/xxx/xxx/images/test.png', data=file)
  File "/home/chiuhongyu/workplace/xxx/venv/lib/python3.6/site-packages/pyhdfs/__init__.py", line 504, in create
    metadata_response.headers['location'], data=data, **self._requests_kwargs)
  File "/home/chiuhongyu/workplace/xxx/venv/lib/python3.6/site-packages/requests/api.py", line 132, in put
    return request('put', url, data=data, **kwargs)
  File "/home/chiuhongyu/workplace/xxx/venv/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/chiuhongyu/workplace/xxx/venv/lib/python3.6/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/chiuhongyu/workplace/xxx/venv/lib/python3.6/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/chiuhongyu/workplace/xxx/venv/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by jingw** [comment]
Hello. HdfsFileAlreadyExistsException is implemented, and you can see in the following test case that it does get raised when appropriate: https://github.com/jingw/pyhdfs/blob/77be5f10dd52ad08bbb1829b65dc05ddf87beefa/test_pyhdfs.py#L226

This error is saying that somebody broke your connection. It is likely something about your network, and is likely unrelated to whether the file exists or not.
